language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
script:
    - python src/manage.py test tickets
    - coverage run src/manage.py test tickets
after_success:
    - coveralls
